### ISSUE TITLE
Add Travis 

### ISSUE THREAD

**Issue by juviwhale** [AppMatch/EntityDetection#2]
This project should be tested via travis

**Comment by teebu** [comment]
@juviwhale https://travis-ci.org/AppMatch/EntityDetection 

`You don't have sufficient rights to enable this repo on Travis. 
Please contact the admin to enable it or to receive admin rights yourself.`

**Comment by teebu** [comment]
if we're making this repo private... will need to add a git key when installing it through the projects.
